displayName=Citizens 2
author=Nick2bad4u,Magnaboy
support=https://github.com/Nick2bad4u/Citizens-2
description=Adds citizens to help bring life to the world (Citizens 2)
tags=citizen,npc,scenery,customization
plugins=com.magnaboy.Citizens2Plugin
